/*
 * Grafana
 * Grafana Restful API.
 *
 * OpenAPI spec version: v1.0
 * Contact: wang@hashdata.cn
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cn.hashdata.grafana.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;

/**
 * Folder
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-17T07:24:04.859Z")
public class Folder {
  @JsonProperty("canAdmin")
  private Boolean canAdmin = null;

  @JsonProperty("canEdit")
  private Boolean canEdit = null;

  @JsonProperty("canSave")
  private Boolean canSave = null;

  @JsonProperty("created")
  private OffsetDateTime created = null;

  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("hasAcl")
  private Boolean hasAcl = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("uid")
  private String uid = null;

  @JsonProperty("updated")
  private OffsetDateTime updated = null;

  @JsonProperty("updatedBy")
  private String updatedBy = null;

  @JsonProperty("url")
  private String url = null;

  @JsonProperty("version")
  private Integer version = null;

  public Folder canAdmin(Boolean canAdmin) {
    this.canAdmin = canAdmin;
    return this;
  }

   /**
   * Get canAdmin
   * @return canAdmin
  **/
  @ApiModelProperty(value = "")
  public Boolean isCanAdmin() {
    return canAdmin;
  }

  public void setCanAdmin(Boolean canAdmin) {
    this.canAdmin = canAdmin;
  }

  public Folder canEdit(Boolean canEdit) {
    this.canEdit = canEdit;
    return this;
  }

   /**
   * Get canEdit
   * @return canEdit
  **/
  @ApiModelProperty(value = "")
  public Boolean isCanEdit() {
    return canEdit;
  }

  public void setCanEdit(Boolean canEdit) {
    this.canEdit = canEdit;
  }

  public Folder canSave(Boolean canSave) {
    this.canSave = canSave;
    return this;
  }

   /**
   * Get canSave
   * @return canSave
  **/
  @ApiModelProperty(value = "")
  public Boolean isCanSave() {
    return canSave;
  }

  public void setCanSave(Boolean canSave) {
    this.canSave = canSave;
  }

  public Folder created(OffsetDateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getCreated() {
    return created;
  }

  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }

  public Folder createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @ApiModelProperty(value = "")
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public Folder hasAcl(Boolean hasAcl) {
    this.hasAcl = hasAcl;
    return this;
  }

   /**
   * Get hasAcl
   * @return hasAcl
  **/
  @ApiModelProperty(value = "")
  public Boolean isHasAcl() {
    return hasAcl;
  }

  public void setHasAcl(Boolean hasAcl) {
    this.hasAcl = hasAcl;
  }

  public Folder id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Folder title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Folder uid(String uid) {
    this.uid = uid;
    return this;
  }

   /**
   * Get uid
   * @return uid
  **/
  @ApiModelProperty(value = "")
  public String getUid() {
    return uid;
  }

  public void setUid(String uid) {
    this.uid = uid;
  }

  public Folder updated(OffsetDateTime updated) {
    this.updated = updated;
    return this;
  }

   /**
   * Get updated
   * @return updated
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getUpdated() {
    return updated;
  }

  public void setUpdated(OffsetDateTime updated) {
    this.updated = updated;
  }

  public Folder updatedBy(String updatedBy) {
    this.updatedBy = updatedBy;
    return this;
  }

   /**
   * Get updatedBy
   * @return updatedBy
  **/
  @ApiModelProperty(value = "")
  public String getUpdatedBy() {
    return updatedBy;
  }

  public void setUpdatedBy(String updatedBy) {
    this.updatedBy = updatedBy;
  }

  public Folder url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public Folder version(Integer version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(value = "")
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Folder folder = (Folder) o;
    return Objects.equals(this.canAdmin, folder.canAdmin) &&
        Objects.equals(this.canEdit, folder.canEdit) &&
        Objects.equals(this.canSave, folder.canSave) &&
        Objects.equals(this.created, folder.created) &&
        Objects.equals(this.createdBy, folder.createdBy) &&
        Objects.equals(this.hasAcl, folder.hasAcl) &&
        Objects.equals(this.id, folder.id) &&
        Objects.equals(this.title, folder.title) &&
        Objects.equals(this.uid, folder.uid) &&
        Objects.equals(this.updated, folder.updated) &&
        Objects.equals(this.updatedBy, folder.updatedBy) &&
        Objects.equals(this.url, folder.url) &&
        Objects.equals(this.version, folder.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canAdmin, canEdit, canSave, created, createdBy, hasAcl, id, title, uid, updated, updatedBy, url, version);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Folder {\n");
    
    sb.append("    canAdmin: ").append(toIndentedString(canAdmin)).append("\n");
    sb.append("    canEdit: ").append(toIndentedString(canEdit)).append("\n");
    sb.append("    canSave: ").append(toIndentedString(canSave)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    hasAcl: ").append(toIndentedString(hasAcl)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("    updatedBy: ").append(toIndentedString(updatedBy)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

