/*
 * Grafana
 * Grafana Restful API.
 *
 * OpenAPI spec version: v1.0
 * Contact: wang@hashdata.cn
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cn.hashdata.grafana.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * GridPos
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-17T07:24:04.859Z")
public class GridPos {
  @JsonProperty("h")
  private Integer h = null;

  @JsonProperty("w")
  private Integer w = null;

  @JsonProperty("x")
  private Integer x = null;

  @JsonProperty("y")
  private Integer y = null;

  public GridPos h(Integer h) {
    this.h = h;
    return this;
  }

   /**
   * Get h
   * @return h
  **/
  @ApiModelProperty(value = "")
  public Integer getH() {
    return h;
  }

  public void setH(Integer h) {
    this.h = h;
  }

  public GridPos w(Integer w) {
    this.w = w;
    return this;
  }

   /**
   * Get w
   * @return w
  **/
  @ApiModelProperty(value = "")
  public Integer getW() {
    return w;
  }

  public void setW(Integer w) {
    this.w = w;
  }

  public GridPos x(Integer x) {
    this.x = x;
    return this;
  }

   /**
   * Get x
   * @return x
  **/
  @ApiModelProperty(value = "")
  public Integer getX() {
    return x;
  }

  public void setX(Integer x) {
    this.x = x;
  }

  public GridPos y(Integer y) {
    this.y = y;
    return this;
  }

   /**
   * Get y
   * @return y
  **/
  @ApiModelProperty(value = "")
  public Integer getY() {
    return y;
  }

  public void setY(Integer y) {
    this.y = y;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GridPos gridPos = (GridPos) o;
    return Objects.equals(this.h, gridPos.h) &&
        Objects.equals(this.w, gridPos.w) &&
        Objects.equals(this.x, gridPos.x) &&
        Objects.equals(this.y, gridPos.y);
  }

  @Override
  public int hashCode() {
    return Objects.hash(h, w, x, y);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GridPos {\n");
    
    sb.append("    h: ").append(toIndentedString(h)).append("\n");
    sb.append("    w: ").append(toIndentedString(w)).append("\n");
    sb.append("    x: ").append(toIndentedString(x)).append("\n");
    sb.append("    y: ").append(toIndentedString(y)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

