/*
 * Grafana
 * Grafana Restful API.
 *
 * OpenAPI spec version: v1.0
 * Contact: wang@hashdata.cn
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cn.hashdata.grafana.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * UpdateDataSourceCommand
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-17T14:29:19.214Z")
public class UpdateDataSourceCommand {
  @JsonProperty("access")
  private String access = null;

  @JsonProperty("basicAuth")
  private Boolean basicAuth = null;

  @JsonProperty("basicAuthPassword")
  private String basicAuthPassword = null;

  @JsonProperty("basicAuthUser")
  private String basicAuthUser = null;

  @JsonProperty("database")
  private String database = null;

  @JsonProperty("default")
  private Boolean _default = null;

  @JsonProperty("jsonData")
  private Map<String, String> jsonData = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("password")
  private String password = null;

  @JsonProperty("readOnly")
  private Boolean readOnly = null;

  @JsonProperty("secureJsonData")
  private Map<String, String> secureJsonData = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("url")
  private String url = null;

  @JsonProperty("user")
  private String user = null;

  @JsonProperty("version")
  private Integer version = null;

  @JsonProperty("withCredentials")
  private Boolean withCredentials = null;

  public UpdateDataSourceCommand access(String access) {
    this.access = access;
    return this;
  }

   /**
   * Get access
   * @return access
  **/
  @ApiModelProperty(value = "")
  public String getAccess() {
    return access;
  }

  public void setAccess(String access) {
    this.access = access;
  }

  public UpdateDataSourceCommand basicAuth(Boolean basicAuth) {
    this.basicAuth = basicAuth;
    return this;
  }

   /**
   * Get basicAuth
   * @return basicAuth
  **/
  @ApiModelProperty(value = "")
  public Boolean isBasicAuth() {
    return basicAuth;
  }

  public void setBasicAuth(Boolean basicAuth) {
    this.basicAuth = basicAuth;
  }

  public UpdateDataSourceCommand basicAuthPassword(String basicAuthPassword) {
    this.basicAuthPassword = basicAuthPassword;
    return this;
  }

   /**
   * Get basicAuthPassword
   * @return basicAuthPassword
  **/
  @ApiModelProperty(value = "")
  public String getBasicAuthPassword() {
    return basicAuthPassword;
  }

  public void setBasicAuthPassword(String basicAuthPassword) {
    this.basicAuthPassword = basicAuthPassword;
  }

  public UpdateDataSourceCommand basicAuthUser(String basicAuthUser) {
    this.basicAuthUser = basicAuthUser;
    return this;
  }

   /**
   * Get basicAuthUser
   * @return basicAuthUser
  **/
  @ApiModelProperty(value = "")
  public String getBasicAuthUser() {
    return basicAuthUser;
  }

  public void setBasicAuthUser(String basicAuthUser) {
    this.basicAuthUser = basicAuthUser;
  }

  public UpdateDataSourceCommand database(String database) {
    this.database = database;
    return this;
  }

   /**
   * Get database
   * @return database
  **/
  @ApiModelProperty(value = "")
  public String getDatabase() {
    return database;
  }

  public void setDatabase(String database) {
    this.database = database;
  }

  public UpdateDataSourceCommand _default(Boolean _default) {
    this._default = _default;
    return this;
  }

   /**
   * Get _default
   * @return _default
  **/
  @ApiModelProperty(value = "")
  public Boolean isDefault() {
    return _default;
  }

  public void setDefault(Boolean _default) {
    this._default = _default;
  }

  public UpdateDataSourceCommand jsonData(Map<String, String> jsonData) {
    this.jsonData = jsonData;
    return this;
  }

  public UpdateDataSourceCommand putJsonDataItem(String key, String jsonDataItem) {
    if (this.jsonData == null) {
      this.jsonData = new HashMap<>();
    }
    this.jsonData.put(key, jsonDataItem);
    return this;
  }

   /**
   * Get jsonData
   * @return jsonData
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getJsonData() {
    return jsonData;
  }

  public void setJsonData(Map<String, String> jsonData) {
    this.jsonData = jsonData;
  }

  public UpdateDataSourceCommand name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public UpdateDataSourceCommand password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @ApiModelProperty(value = "")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public UpdateDataSourceCommand readOnly(Boolean readOnly) {
    this.readOnly = readOnly;
    return this;
  }

   /**
   * Get readOnly
   * @return readOnly
  **/
  @ApiModelProperty(value = "")
  public Boolean isReadOnly() {
    return readOnly;
  }

  public void setReadOnly(Boolean readOnly) {
    this.readOnly = readOnly;
  }

  public UpdateDataSourceCommand secureJsonData(Map<String, String> secureJsonData) {
    this.secureJsonData = secureJsonData;
    return this;
  }

  public UpdateDataSourceCommand putSecureJsonDataItem(String key, String secureJsonDataItem) {
    if (this.secureJsonData == null) {
      this.secureJsonData = new HashMap<>();
    }
    this.secureJsonData.put(key, secureJsonDataItem);
    return this;
  }

   /**
   * Get secureJsonData
   * @return secureJsonData
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getSecureJsonData() {
    return secureJsonData;
  }

  public void setSecureJsonData(Map<String, String> secureJsonData) {
    this.secureJsonData = secureJsonData;
  }

  public UpdateDataSourceCommand type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public UpdateDataSourceCommand url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public UpdateDataSourceCommand user(String user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @ApiModelProperty(value = "")
  public String getUser() {
    return user;
  }

  public void setUser(String user) {
    this.user = user;
  }

  public UpdateDataSourceCommand version(Integer version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(value = "")
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }

  public UpdateDataSourceCommand withCredentials(Boolean withCredentials) {
    this.withCredentials = withCredentials;
    return this;
  }

   /**
   * Get withCredentials
   * @return withCredentials
  **/
  @ApiModelProperty(value = "")
  public Boolean isWithCredentials() {
    return withCredentials;
  }

  public void setWithCredentials(Boolean withCredentials) {
    this.withCredentials = withCredentials;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateDataSourceCommand updateDataSourceCommand = (UpdateDataSourceCommand) o;
    return Objects.equals(this.access, updateDataSourceCommand.access) &&
        Objects.equals(this.basicAuth, updateDataSourceCommand.basicAuth) &&
        Objects.equals(this.basicAuthPassword, updateDataSourceCommand.basicAuthPassword) &&
        Objects.equals(this.basicAuthUser, updateDataSourceCommand.basicAuthUser) &&
        Objects.equals(this.database, updateDataSourceCommand.database) &&
        Objects.equals(this._default, updateDataSourceCommand._default) &&
        Objects.equals(this.jsonData, updateDataSourceCommand.jsonData) &&
        Objects.equals(this.name, updateDataSourceCommand.name) &&
        Objects.equals(this.password, updateDataSourceCommand.password) &&
        Objects.equals(this.readOnly, updateDataSourceCommand.readOnly) &&
        Objects.equals(this.secureJsonData, updateDataSourceCommand.secureJsonData) &&
        Objects.equals(this.type, updateDataSourceCommand.type) &&
        Objects.equals(this.url, updateDataSourceCommand.url) &&
        Objects.equals(this.user, updateDataSourceCommand.user) &&
        Objects.equals(this.version, updateDataSourceCommand.version) &&
        Objects.equals(this.withCredentials, updateDataSourceCommand.withCredentials);
  }

  @Override
  public int hashCode() {
    return Objects.hash(access, basicAuth, basicAuthPassword, basicAuthUser, database, _default, jsonData, name, password, readOnly, secureJsonData, type, url, user, version, withCredentials);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateDataSourceCommand {\n");
    
    sb.append("    access: ").append(toIndentedString(access)).append("\n");
    sb.append("    basicAuth: ").append(toIndentedString(basicAuth)).append("\n");
    sb.append("    basicAuthPassword: ").append(toIndentedString(basicAuthPassword)).append("\n");
    sb.append("    basicAuthUser: ").append(toIndentedString(basicAuthUser)).append("\n");
    sb.append("    database: ").append(toIndentedString(database)).append("\n");
    sb.append("    _default: ").append(toIndentedString(_default)).append("\n");
    sb.append("    jsonData: ").append(toIndentedString(jsonData)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    readOnly: ").append(toIndentedString(readOnly)).append("\n");
    sb.append("    secureJsonData: ").append(toIndentedString(secureJsonData)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    withCredentials: ").append(toIndentedString(withCredentials)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

